#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import sys
import argparse
sys.path.append('/usr/lib/wrtd')
from wrt_param import WrtParam
from wrt_cmd import WrtSubCmdMain


def parseArgs():
    argParser = argparse.ArgumentParser()
    subParsers = argParser.add_subparsers()

    apShow = subParsers.add_parser("show")
    apShow.set_defaults(subcmd="show")

    apServerGenClientCert = subParsers.add_parser("generate-client-script")
    apServerGenClientCert.set_defaults(subcmd="generate-client-script")
    apServerGenClientCert.add_argument("vpns_type", metavar="vpn-server-type")
    apServerGenClientCert.add_argument("os_type", metavar="os-type")

    return argParser.parse_args()

################################################################################

param = WrtParam()
parseResult = parseArgs()

# some assistant sub command
if parseResult.subcmd == "show":
    WrtSubCmdMain(param).cmdShow()
elif parseResult.subcmd == "generate-client-script":
    WrtSubCmdMain(param).cmdGenerateClientScript(parseResult.vpns_type, parseResult.os_type)
else:
    raise Exception("Invalid command")